spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/company_eat_db?useUnicode=true&characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
#    加了这句然后为null的东西就不会返回，比如orderDetailList为null就不会返回了
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
